### ISSUE TITLE
【建议】增加json key 驼峰和下划线选择配置

### ISSUE THREAD

**Issue by hh-Ink** [essrt/gentoolplus#1]
增加json key 驼峰和下划线选择配置

如：
```go
// 默认配置

type Language struct {
	ID        int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary Key" json:"id"` // Primary Key
	CreatedAt *time.Time `gorm:"column:created_at;comment:Create Time" json:"created_at"`               // Create Time
	Name      string     `gorm:"column:name;not null" json:"name"`
	StaffID   *int64     `gorm:"column:staff_id" json:"staff_id"`
	User      []User     `gorm:"many2many:user_languages" json:"user"`
}


// 配置了驼峰

type Language struct {
	ID        int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary Key" json:"id"` // Primary Key
	CreatedAt *time.Time `gorm:"column:created_at;comment:Create Time" json:"createdAt"`               // Create Time
	Name      string     `gorm:"column:name;not null" json:"name"`
	StaffID   *int64     `gorm:"column:staff_id" json:"staffId"`
	User      []User     `gorm:"many2many:user_languages" json:"user"`
}

```

**Comment by essrt** [comment]
> 增加json key 驼峰和下划线选择配置
> 
> 如：
> 
> ```go
> // 默认配置
> 
> type Language struct {
> 	ID        int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary Key" json:"id"` // Primary Key
> 	CreatedAt *time.Time `gorm:"column:created_at;comment:Create Time" json:"created_at"`               // Create Time
> 	Name      string     `gorm:"column:name;not null" json:"name"`
> 	StaffID   *int64     `gorm:"column:staff_id" json:"staff_id"`
> 	User      []User     `gorm:"many2many:user_languages" json:"user"`
> }
> 
> 
> // 配置了驼峰
> 
> type Language struct {
> 	ID        int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary Key" json:"id"` // Primary Key
> 	CreatedAt *time.Time `gorm:"column:created_at;comment:Create Time" json:"createdAt"`               // Create Time
> 	Name      string     `gorm:"column:name;not null" json:"name"`
> 	StaffID   *int64     `gorm:"column:staff_id" json:"staffId"`
> 	User      []User     `gorm:"many2many:user_languages" json:"user"`
> }
> ```

我考虑一下

**Comment by essrt** [comment]
我更新了增加了一个json tag 的驼峰命名格式的开关，不使用的话默认与数据库表字段格式一致。
