### ISSUE TITLE
安装异常

### ISSUE THREAD

**Issue by hh-Ink** [essrt/gentoolplus#2]
### 安装指令
```
go get -u github.com/essrt/gentoolplus@latest
```

#### 异常
```
go: github.com/essrt/gentoolplus@latest (v1.0.0) requires github.com/essrt/gentoolplus@v1.0.0: parsing go.mod: go.mod:12:2: usage: require module/path v1.2.3
```

**Comment by essrt** [comment]
可以直接用go install github.com/essrt/gentoolplus  下载一个可执行文件

**Comment by essrt** [comment]
> 可以直接用go install github.com/essrt/gentoolplus 下载一个可执行文件

用go get -u github.com/essrt/gentoolplus@1.0.0，然后用go install ，会在你的GOPATH中下载一个可执行文件
